//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookworm_Desktop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TCCFEntities : DbContext
    {
        public TCCFEntities()
            : base("name=TCCFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCargo> tblCargo { get; set; }
        public virtual DbSet<tblEmprestimo> tblEmprestimo { get; set; }
        public virtual DbSet<tblEvento> tblEvento { get; set; }
        public virtual DbSet<tblFuncionario> tblFuncionario { get; set; }
        public virtual DbSet<tblGenero> tblGenero { get; set; }
        public virtual DbSet<tblLeitor> tblLeitor { get; set; }
        public virtual DbSet<tblProduto> tblProduto { get; set; }
        public virtual DbSet<tblTipoLeitor> tblTipoLeitor { get; set; }
        public virtual DbSet<tblReserva> tblReserva { get; set; }
        public virtual DbSet<tblFavoritos> tblFavoritos { get; set; }
        public virtual DbSet<tblGeneroProduto> tblGeneroProduto { get; set; }
    }
}
