//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookworm_Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProduto()
        {
            this.tblEmprestimo = new HashSet<tblEmprestimo>();
            this.tblReserva = new HashSet<tblReserva>();
            this.tblFavoritos = new HashSet<tblFavoritos>();
            this.tblGeneroProduto = new HashSet<tblGeneroProduto>();
        }
    
        public int IDProduto { get; set; }
        public int TipoAcervo { get; set; }
        public string NomeLivro { get; set; }
        public string AutoresLivro { get; set; }
        public Nullable<System.DateTime> AnoEdicao { get; set; }
        public int Setor { get; set; }
        public int Fileira { get; set; }
        public int Prateleira { get; set; }
        public string TipoProduto { get; set; }
        public string Editora { get; set; }
        public string DescricaoProd { get; set; }
        public byte[] ImagemProd { get; set; }
        public string ISBN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmprestimo> tblEmprestimo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReserva> tblReserva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFavoritos> tblFavoritos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGeneroProduto> tblGeneroProduto { get; set; }
    }
}
